[WIP] Fix #384: Recherche de propriétés
voyages-sncf-technologies/hesperides pull request #867
Opened 2020-11-24 09:03 UTC by thomaslhostis

2020-11-24 10:02 UTC, Lucas-C requested changes

2020-11-24 10:02 UTC, Lucas-C commented on documentation/lightweight-architecture-decision-records/search_properties.md
> +Si aucune des deux premières solutions n'est acceptable au niveau des performances, nous envisageons de forcer la sélection d'une application sur laquelle faire la recherche dans un premier temps.
Je complèterai bien par : _"afin d'employer un filtrage par l'application en mémoire (= en Java, solution n°2), en limitant le risque de consommer trop de RAM"_

2020-11-24 10:02 UTC, Lucas-C commented on documentation/lightweight-architecture-decision-records/search_properties.md
> +### Créer une vue à l'aide des évènements de l'application
👍

2020-11-24 10:02 UTC, Lucas-C commented on documentation/lightweight-architecture-decision-records/search_properties.md
> +* Une mise en place coûteuse en temps
Et en volume de code je pense.
D'ailleurs, l'insertion des données dans cette vue se ferait comment / à quelle niveau dans le code ?

2020-11-24 10:22 UTC, Lucas-C commented on documentation/lightweight-architecture-decision-records/search_properties.md
> +* Cacher les valeurs des propriétés de type mot de passe pour les utilisateurs non habilités
Une remarque très pertinente de Gilles : est-ce qu'on souhaite pouvoir **rechercher des mots de passe par nom ou valeur** ?

2020-11-24 10:33 UTC, thomaslhostis commented on documentation/lightweight-architecture-decision-records/search_properties.md
> +* Potentiellement coûteux en mémoire
C'est ça. Si j'ai bien compris, le framework d'agrégation MongoDB crée sa propre vue en mémoire avant d'appliquer le filtre définitif. Sur un gros volume de données rapatriées, c'est coûteux en mémoire.

2020-11-24 11:07 UTC, thomaslhostis commented on documentation/lightweight-architecture-decision-records/search_properties.md
> +Cette solution est envisagée pour sa facilité de mise en œuvre (donc sa maintenabilité) et parce qu'elle est potentiellement moins coûteuse en termes de mémoire que la solution précédente.
C'est une erreur de ma part. En fait les 2 solutions sont potentiellement coûteuses en mémoire. La solution Agrégation serait juste plus performante (à vérifier).

Un autre inconvénient de la solution Java est de dupliquer une partie du filtre.

Le filtre sur les propriétés recherchées (par nom et/ou valeur) est appliqué sur la requête qui nous retourne les plateformes contenant ces propriétés, il faut donc ensuite filtrer en Java les propriétés pour ne retourner que celles qui sont concernées par la recherche

Je vais modifier ça.

2020-11-30 09:46 UTC, thomaslhostis commented on documentation/lightweight-architecture-decision-records/search_properties.md
> +
J'ai ajouté une section [Évolutions envisagée](https://github.com/voyages-sncf-technologies/hesperides/blob/issue_384/documentation/lightweight-architecture-decision-records/search_properties.md#%C3%A9volutions-envisag%C3%A9es).

2020-11-30 09:48 UTC, thomaslhostis commented on documentation/lightweight-architecture-decision-records/search_properties.md
> +L'inconvénient principal de cette solution serait de faibles performances.
J'ai revu un peu cette section : https://github.com/voyages-sncf-technologies/hesperides/blob/issue_384/documentation/lightweight-architecture-decision-records/search_properties.md#filtre-java

2020-11-30 09:54 UTC, thomaslhostis commented on documentation/lightweight-architecture-decision-records/search_properties.md
> +* Une mise en place coûteuse en temps
Je ne sais pas exactement mais sur le principe il faut ajouter des handlers aux évènements qui mettent à jour les valorisations de propriétés.

2020-11-30 09:55 UTC, thomaslhostis commented on documentation/lightweight-architecture-decision-records/search_properties.md
> +* Cacher les valeurs des propriétés de type mot de passe pour les utilisateurs non habilités
En effet, j'ai ajouté un point dans les règles spécifiques : https://github.com/voyages-sncf-technologies/hesperides/blob/issue_384/documentation/lightweight-architecture-decision-records/search_properties.md#r%C3%A8gles-sp%C3%A9cifiques

2020-12-01 09:05 UTC, Lucas-C commented on documentation/lightweight-architecture-decision-records/search_properties.md
> +  * Si l'utilisateur n'a pas les droits de prod et que la recherche est faite sur la valeur des propriétés, on ne retourne pas les mots de passe de prod ayant cette valeur
👍 👍 👍

2020-12-02 16:40 UTC, Lucas-C approved these changes

2020-12-02 16:40 UTC, Lucas-C commented on core/application/src/main/java/org/hesperides/core/application/platforms/PropertiesUseCases.java
> +        if (!user.isGlobalProd()) {
👍

2020-12-02 16:40 UTC, Lucas-C commented on core/application/src/main/java/org/hesperides/core/application/platforms/PropertiesUseCases.java
> +                    .distinct()
Pourquoi ? Quand peut-il y avoir des duplicats ?

2020-12-02 16:40 UTC, Lucas-C commented on core/application/src/main/java/org/hesperides/core/application/platforms/PropertiesUseCases.java
> +            Map<Module.Key, List<String>> passwordsByModule = moduleQueries.findPasswordPropertiesIn(moduleKeys)
Micro optimisation: `Map<Module.Key, Set<String>>` ?
Avec un `Set` on sera un poil plus efficace pour tester, plus tard dans le code, si une propriété est contenue dedans.

2020-12-02 16:40 UTC, Lucas-C commented on core/infrastructure/src/main/java/org/hesperides/core/infrastructure/mongo/platforms/MongoPlatformRepository.java
> +    @Query(value = "{ 'deployedModules.valuedProperties.name': ?0 }", fields = SEARCHED_PROPERTIES_FIELDS)
Quel intérêt d'avoir 3 requêtes distinctes ici, plutôt que d'employer uniquement la 3e ?
De meilleures performances ?

2020-12-02 16:40 UTC, Lucas-C commented on core/infrastructure/src/main/java/org/hesperides/core/infrastructure/mongo/platforms/documents/AbstractValuedPropertyDocument.java
> -    private static boolean propertyHasValue(String propertyName, List<AbstractValuedPropertyDocument> abstractValuedProperties) {
👍 Bon débarras :)

2020-12-02 16:40 UTC, Lucas-C commented on core/presentation/src/main/java/org/hesperides/core/presentation/controllers/PropertiesController.java
> +            throw new IllegalArgumentException("Veuillez saisir le nom et/ou la valeur de la propriété à rechercher");
Les messages d'erreur sont en anglais en général dans l'appli, non ?

2020-12-02 16:40 UTC, Lucas-C commented on pom.xml
> +        <kotlin.version>1.4.20</kotlin.version>
👍

2020-12-02 16:40 UTC, Lucas-C commented on tests/bdd/src/test/resources/platforms/properties/search-properties.feature
> +  Scenario: trying to search properties without a name or a value should fail
👍

2020-12-02 16:40 UTC, Lucas-C commented on tests/bdd/src/test/resources/platforms/properties/search-properties.feature
> +  Scenario: search a property by name in archived module
👍 👍 
Par je remplacerais bien "archived" par "unused"

2020-12-02 16:40 UTC, Lucas-C commented on tests/bdd/src/test/resources/platforms/properties/search-properties.feature
> +  Scenario: search a property in multiple applications
Bonne idée, mais je trouverais + intéressant de tester le comportement où il y a un plus grand risque de résultats dupliqués, par exemple une valeur de propriété employée à 2 endroits dans un même module déployé.
Qu'en penses-tu ?

2020-12-02 16:55 UTC, thomaslhostis commented on core/application/src/main/java/org/hesperides/core/application/platforms/PropertiesUseCases.java
> +                    .distinct()
Si la recherche est faite sur la valeur d'une propriété, il peut y avoir plusieurs propriétés ayant la même valeur dans un même module déployé :)

2020-12-02 16:58 UTC, thomaslhostis commented on core/application/src/main/java/org/hesperides/core/application/platforms/PropertiesUseCases.java
> +            Map<Module.Key, List<String>> passwordsByModule = moduleQueries.findPasswordPropertiesIn(moduleKeys)
Bien vu 👍

2020-12-02 17:01 UTC, thomaslhostis commented on core/application/src/main/java/org/hesperides/core/application/platforms/PropertiesUseCases.java
> +            Map<Module.Key, List<String>> passwordsByModule = moduleQueries.findPasswordPropertiesIn(moduleKeys)
https://github.com/voyages-sncf-technologies/hesperides/pull/867/commits/96799fb5d21cafcdcc10cfcaf4933cb1a1a121b3

2020-12-02 17:04 UTC, thomaslhostis commented on core/infrastructure/src/main/java/org/hesperides/core/infrastructure/mongo/platforms/MongoPlatformRepository.java
> +    @Query(value = "{ 'deployedModules.valuedProperties.name': ?0 }", fields = SEARCHED_PROPERTIES_FIELDS)
Le problème est de gérer le cas où l'une des deux valeurs n'est pas renseignée. Je n'ai pas réussi à faire ça en une seule requête. Mes compétences en requêtes Mongo sont très limitées mais j'ai bonne espoir de m'améliorer avec ceci : https://blog.jetbrains.com/datagrip/2020/10/22/datagrip-2020-3-eap-3-sql-for-mongodb/

2020-12-02 17:07 UTC, thomaslhostis commented on core/presentation/src/main/java/org/hesperides/core/presentation/controllers/PropertiesController.java
> +            throw new IllegalArgumentException("Veuillez saisir le nom et/ou la valeur de la propriété à rechercher");
Bien vu

2020-12-02 17:09 UTC, thomaslhostis commented on tests/bdd/src/test/resources/platforms/properties/search-properties.feature
> +  Scenario: search a property by name in archived module
On utilise le terme "unused" pour les propriétés orphelines. Bien qu'on n'ait jamais utilisé "archived module" en dehors de l'API, c'est bien le terme qu'on emploie : https://github.com/voyages-sncf-technologies/hesperides/blob/a5ad3fc3c68dffdb8dbf6bff8064d505d61bdf97/core/infrastructure/src/main/java/org/hesperides/core/infrastructure/mongo/platforms/documents/PlatformDocument.java#L46

2020-12-02 17:15 UTC, thomaslhostis commented on tests/bdd/src/test/resources/platforms/properties/search-properties.feature
> +  Scenario: search a property in multiple applications
https://github.com/voyages-sncf-technologies/hesperides/blob/issue_384/tests/bdd/src/test/resources/platforms/properties/search-properties.feature#L22

Comme ceci ?

2020-12-02 17:17 UTC, thomaslhostis commented on core/presentation/src/main/java/org/hesperides/core/presentation/controllers/PropertiesController.java
> +            throw new IllegalArgumentException("Veuillez saisir le nom et/ou la valeur de la propriété à rechercher");
https://github.com/voyages-sncf-technologies/hesperides/pull/867/commits/d089d3c65e37f45e4b5095b1bf1b8179199333b3

2020-12-03 08:05 UTC, Lucas-C commented on core/infrastructure/src/main/java/org/hesperides/core/infrastructure/mongo/platforms/MongoPlatformRepository.java
> +    @Query(value = "{ 'deployedModules.valuedProperties.name': ?0 }", fields = SEARCHED_PROPERTIES_FIELDS)
:D

2020-12-03 08:05 UTC, Lucas-C commented on tests/bdd/src/test/resources/platforms/properties/search-properties.feature
> +  Scenario: search a property by name in archived module
Je crois qu'il y a confusion... On s'appelle dans la journée pour en parler rapido ?

2020-12-03 08:06 UTC, Lucas-C commented on tests/bdd/src/test/resources/platforms/properties/search-properties.feature
> +  Scenario: search a property in multiple applications
Ah bah... oui 🤦‍♂️ ;)

2020-12-03 08:09 UTC, thomaslhostis commented on tests/bdd/src/test/resources/platforms/properties/search-properties.feature
> +  Scenario: search a property by name in archived module
D'accord :)

2020-12-03 11:18 UTC, Lucas-C commented on tests/bdd/src/test/resources/platforms/properties/search-properties.feature
> +  Scenario: search a property by name in archived module
Ok, c'est tout bon !

2020-12-03 15:44 UTC, merged